# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='updload_location', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='page',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
