# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160526_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='about_us',
            field=models.TextField(default='about us', max_length=240),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(default='description', max_length=240),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='title', max_length=120),
        ),
        migrations.AddField(
            model_name='page',
            name='what_we_do',
            field=models.TextField(default='what we do', max_length=240),
        ),
    ]
