# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=120)),
                ('telephone', models.CharField(default='telephone', max_length=120)),
                ('email', models.CharField(default='email', max_length=120)),
                ('message', models.TextField(default='message', max_length=240)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
